defaults:
  - base
  - _self_

use_pretrained: true

dataset: cifar10
num_labels: 10

learning_rate: 5e-4
batch_size: 16
local_steps: 700
max_train_samples: 8000
max_eval_samples: 1000
homogeneity: 1.0
num_clients: 5
num_rounds: 5
matcher: null
