defaults:
  - base
  - _self_

run_name: fedavg-scratch-imagenet1k
use_pretrained: false

dataset: imagenet1k
num_labels: 1000
max_train_samples: 80_000
max_eval_samples: 10_000

batch_size: 64
learning_rate: 5e-4
local_steps: 700

homogeneity: 1.0
num_clients: 10
num_rounds: 10

matcher: null